config/routes.rb
Museum::Application.routes.draw do
  get "home/index"
  get "home/output"

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	respond_to do |format|
      format.html
      format.js
    end
  end

  def output
  	input_symbol = params[:symbol]
  	start_date = params[:start_date]
  	end_date = params[:end_date]
  	type = params[:type].to_sym
    indicator = params[:indicator].to_sym
    variables = params[:variables].split(" ")
    @query = Array.new
    begin
      begin
  		  @history_data = Securities::Stock.new(:symbol => input_symbol, :start_date => start_date, :end_date => end_date, :type => type).output
        @query << "history_data = Securities::Stock.new(:symbol => '#{input_symbol}', :start_date => '#{start_date}', :end_date => '#{end_date}', :type => :#{type}).output"
        @symbol = input_symbol
        @lookup = Securities::Lookup.new(input_symbol).output[0]
        @query << "Securities::Lookup.new('#{input_symbol}').output[0]"
      rescue Exception => exc
        if exc.message == 'Stock symbol does not exist.'
          @lookup = Securities::Lookup.new(input_symbol).output[0]
          @symbol = @lookup[:symbol]
          @query << "Securities::Lookup.new('#{input_symbol}').output[0]"
          @history_data = Securities::Stock.new(:symbol => @symbol, :start_date => start_date, :end_date => end_date, :type => type).output
          flash.now[:warning] = "'#{input_symbol}' does not exist. Did you mean #{@symbol}?"
          @query << "history_data = Securities::Stock.new(:symbol => '#{@symbol}', :start_date => '#{start_date}', :end_date => '#{end_date}', :type => :#{type}).output"
        end
      end
      unless indicator == :none
        indicator_data = Indicators::Data.new(@history_data).calc(:type => indicator, :params => variables)
        @query << "Indicators::Data.new(history_data).calc(:type => :#{indicator}, :params => #{variables})"
        @indicator_output = indicator_data.output
        @indicator_abbr = indicator_data.abbr
        @indicator_params = indicator_data.params
        if indicator == :bb
          @indicator_name = ["middle band", "upper band", "lower band"]
        elsif indicator == :macd
          @indicator_name = ["macd line", "signal line", "macd histogram"]
        elsif indicator == :sto
          @indicator_name = ["fast %K", "slow %K", "full %D"]
        else 
          @indicator_name = indicator
        end
      end
    rescue Exception => exc
      if exc.message == 'There were no results for this lookup.'
        flash.now[:error] = "Stock symbol does not exist and a query for similar symbols returned nothing."
      elsif exc.message == 'Stock symbol does not exist.'
        flash.now[:error] = "Yahoo Finance does not provide history data for this symbol."
      else
        flash.now[:error] = "#{exc.message}"
      end
    end

    # If symbol doesn't exist or returned no results from securities.

		respond_to do |format|
      format.html
      format.js
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_input.html.erb
<%= form_tag(home_output_path, :method => "get", :remote => :true) do %>
  <%= text_field_tag :symbol, nil, :class => "input-xxlarge", :placeholder => "stock symbol or name" %>
  <%= text_field_tag :start_date, Date.today - 3.month, :type => "date", :placeholder => "start date" %>
  <%= text_field_tag :end_date, Date.today, :class => "date", :placeholder => "end date" %>
  <%= select_tag :type, "<option>daily</option><option>weekly</option><option>monthly</option><option>dividends</option>".html_safe %>
  <%= select_tag :indicator, "<option>none</option><option>sma</option><option>ema</option><option>bb</option><option>macd</option><option>rsi</option><option>sto</option>".html_safe %>
  <%= text_field_tag :variables, "", :placeholder => "parameters seperated with spaces (i.e. 20 2 for BB; 12 26 9 for MACD)" %>
  <br>
  <!-- TODO: Add loading animation to the button -->
  <%= submit_tag "Results", :class => "btn btn-large btn-block btn-primary"%>
<% end %>
<!-- TODO: find alternative to make "Clean" button work with ajax -->
<%= button_to "Clean", root_url, :class => "btn btn-warning"%>

app/views/home/_results.html.erb
<% if flash[:error] %>
	<div class="alert alert-error"><%= flash[:error] %></div>
<% elsif flash[:warning] %>
	<div class="alert"><%= flash[:warning] %></div>
<% end %>
<% unless @history_data.nil? %>
	Query DSL used:<br>
	<% @query.each do |z| %>
		<code><%=	z %></code><br>
	<% end %>
	<p><%= "#{@lookup[:name]} [#{@lookup[:type].downcase} symbol #{@symbol.upcase}], industry - #{@lookup[:industry_category]}, exchange - #{@lookup[:exchange]}." %></p>
	<table class="table">
		<% @history_data.each_with_index do |row, index| %>
			<% if index == 0 %>
				<!-- Header line -->
				<tr>
					<% row.each_key do |key| %>
						<th>
							<%= key %>
						</th>
					<% end %>
					<% unless @indicator_output.nil? %>

						<p align="right"><%= @indicator_abbr %> with parameters: <%= @indicator_params %></p>
						<% if @indicator_name.is_a?(Array) %>
							<% @indicator_name.each do |name| %>
								<th>
									<%= name %>
								</th>
							<% end %>
						<% else %>
							<th>
								<%= @indicator_name %>
							</th>
						<% end %>

					<% end %>
				</tr>

			<% end %>

			<tr>
				<% row.each do |column, value| %>
					<td>
						<%= value %>
					</td>
				<% end %>

				<% unless @indicator_output.nil? %>

						<% if @indicator_output[index].is_a?(Array) %>
								<% @indicator_output[index].each do |data| %>
									<td>
										<%= data.round(3) unless data.nil? %>
									</td>
								<% end %>
						<% else %>
								<td>
									<%= @indicator_output[index].round(3) unless @indicator_output[index].nil? %>
								</td>
						<% end %>

				<% end %>

			</tr>
		<% end %>
	</table>
<% end %>
<%= debug(params) if Rails.env.development? %>

app/views/home/index.html.erb
<h1>Museum</h1>
<p>Financial analysis tool.</p>

<%= render :partial => "input" %>
<div id="output">
	<%= render :partial => "results" %>
</div>

app/views/home/index.js.erb
$(function() {
  $('#output').html("<%= escape_javascript(render('input')) %>");
});

app/views/home/output.html.erb
<%= render :partial => "input" %>
<%= render :partial => "results" %>

app/views/home/output.js.erb
$(function() {
  $('#output').html("<%= escape_javascript(render('results')) %>");
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Museum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="hero-unit">
<%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>
</body>
</html>